services:
  aigateway:
    build: .
    container_name: aigateway       
    network_mode: host           
    volumes:
      - /data/aigatewaytrans/:/app/ 
      - ./logs:/var/log/aigateway  
    env_file: .env
    environment:
      AIGATEWAY_LOG_FILE: /var/log/aigateway/app.log  
    restart: unless-stopped

volumes:
  aigateway-logs:  
